### ISSUE TITLE
Use bibtool to change the key in arxive2bib

### ISSUE THREAD

**Issue by ANaumann85** [gerw/mathbin#2]
The arxive2bib tool provides a bib entry with the arxive number as key. We can use [bibtool](https://ctan.org/pkg/bibtool) to extract the author names and year automatically. The tool is available as packages on the major distributions Debian, Ubuntu, Fedora and Suse.

The code
```
#if we have bibtool (https://ctan.org/pkg/bibtool) we can use it to format the key
if [ -x "$(command -v bibtool)" ] ; then
        wget -O - $URL -q | xmllint  --xpath '//div[@id="biblatex"]/textarea/text()' - | bibtool -f "%n(author):%4d(year)" -- "new.entry.type {online}"
else
        wget -O - $URL -q | xmllint  --xpath '//div[@id="biblatex"]/textarea/text()' -
fi
```
also checks if the tool is available and then formats the bibfile accordingly. Please note the new entry type at the very end. The arxive-api provides the entry type "online", which is not known to bibtool.

**Comment by gerw** [comment]
Nice idea, thank you!
