### ISSUE TITLE
Error with lxml on Mac OS Big Sur

### ISSUE THREAD

**Issue by kellertuer** [gerw/mathbin#5]
I get an error when using `doi2pdf` on Mac OS Big Sur (Python 3.9.2, lxml installed via pip3,

```
  File "mathbin/doi2pdfname.py", line 9, in <module>
    tree = etree.parse(sys.argv[1], parser=parser)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/tmp/81657250", line 47
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 47, column 93
```

Also I get a print of the usage for grep (installed grep via homebrew) - is that intended?

My example call is `doi2pdf 10.1016/j.cam.2016.07.018`.

**Comment by gerw** [comment]
I cannot reproduce. The XML file from `dx.doi.org` does not contain `nbsp` for me.

Can you post the content of the temporary file (`/tmp/81657250` above)? You have to call
````
curl -sL -H "Accept: application/vnd.crossref.unixsd+xml" http://dx.doi.org/10.1016/j.cam.2016.07.018 > /tmp/81657250
````
before.

**Comment by kellertuer** [comment]
Thanks for the fast response – the content I get is https://gist.github.com/kellertuer/cb21abeac606b14c4a69c7e79f7e749a (after running your call). 

But running the `doi2pdf` command again and opening the `tmp` file, the problem is, that I seem to retrieve a html file instead https://gist.github.com/kellertuer/001571ed560c4b6f4e78d13b0931def6.

Let me know how I can help further, I am not that experienced with shell scripts and all the involved tools (and which might be missing on Mac OS).

**Comment by gerw** [comment]
I don't know. Somehow, you do not get the xml from dx.doi.org but rather a standard page on which you can enter a doi number. This does not seem to be a bug in `doi2pdf`.

**Comment by kellertuer** [comment]
So I think i found the issue and solution. The problem is that the mac OS `grep` does not have a `-P` option. So one can install the gnu grep via homebrew using `brew install grep` but that installs it as `ggrep` (See also https://formulae.brew.sh/formula/grep). So with the line

```
export PATH="$(brew --prefix)/opt/grep/libexec/gnubin:$PATH"
```

added to `.zshrc` one can get the gnu grep as normal grep command in mac os. 

So you are right, this was not a bug in `doi2pdf`, it just means that currently the mathbin scripts are not compatible with Mac OS.
